### ISSUE TITLE
Atualizar o convite do README

### ISSUE THREAD

**Issue by ImGabe** [VaryBot/Vary#49]
O convite para o servidor do Bot está indisponível.

![convite](https://i.imgur.com/Kx6Ghy6.png)

**Comment by ItsDiogo912** [comment]
Podemos saber qual é o comando onde está o convite inválido?

**Comment by ImGabe** [comment]
Como falei, não é nenhum comando, os convites no README estão indisponíveis.[imagem_do_convite_no_readme](https://user-images.githubusercontent.com/24387926/64551337-2d529a80-d30b-11e9-885a-89139ebc7761.png)

**Comment by ItsDiogo912** [comment]
Iremos atualizar o invite...
Obrigado por nos ajudar a melhorar 👍

**Comment by ImGabe** [comment]
Ainda falta arrumar dois convites, um na parte de **ideias** e o outro na parte de **bugs**. Eles possuem código `hVBfjn35`, no caso: `https://discordapp.com/invite/VBfjn35`.

**Comment by ItsDiogo912** [comment]
Editando....

**Comment by ItsDiogo912** [comment]
Em mais algum lado?

**Comment by ImGabe** [comment]
Não, agora está tudo funcionando. 👌
